<?php include "inlcludes/config.php"; ?>
<?php include "config.php"; ?>

<?php include "header.php"; ?>
<?php 


	$DrinkId = trim($_GET['DrinkId']); // Get the DrinkId from the finddrinks page the user clicked on.

	@ $db = new mysqli($dbserver, $dbuser, $dbpass, $dbname); // Connect to the database
	if ($db->connect_error) {
		echo "could not connect: " . $db->connect_error;
		print("<br><a href=index.php>Return to home page </a>");
		exit();
	}

	function test() {
		echo "hej";
	}

	// GET ALL THE INFORMATION TO DISPLAY THEM 
	$query = " SELECT Drinks.DrinkId, Drinks.DrinkName, Drinks.DrinkAuthor, Drinks.DrinkPicture, Drinks.DrinkReceipt, Ingredients.IngId, Ingredients.NameIng
	FROM Drinks 
	JOIN DrinksIng ON Drinks.DrinkId = DrinksIng.DrinkId
	JOIN Ingredients ON Ingredients.IngId = DrinksIng.IngId 
	WHERE Drinks.DrinkId=$DrinkId" ; // Get all the informartion related to the drinkid

	$result = $db->query($query);
	$stmt = $db->prepare($query);
	$stmt->bind_result($DrinkId, $DrinkName, $DrinkAuthor, $DrinkPicture, $DrinkReceipt, $IngId, $NameIng); // Same as the query. 
	$stmt->execute();
	$alling=array(); // Create an array in reason to store all the differents ingredients. 

	while ($stmt->fetch()) {
		array_push($alling,$NameIng); // Put the ingredients in the array
	}

	// GET ALL THE INFORMATION TO DISPLAY THEM 
	//Add one ingredient

			if(isset($_POST['addIng'])){

				@ $db = new mysqli($dbserver, $dbuser, $dbpass, $dbname);

				if ($db->connect_error) {
					echo "could not connect: " . $db->connect_error;
					print("<br><a href=index.php>Return to home page </a>");
					exit();
				}

				$NewNameIng = $_POST['NameIng'];

				$addIng = "INSERT INTO Ingredients(NameIng) VALUES(?);";

				$stmt = $db->prepare($addIng);
				$stmt->bind_param('s',$NewNameIng);
				$stmt->execute(); 
				header('location:update.php');

			}
			// Get all ingredients 
			$getIng = "SELECT * FROM Ingredients";
			
			$stmt = $db->prepare($getIng);
			$stmt->bind_result($IngId, $NameIng);
			$stmt->execute();



			if(isset($_POST['updateDrink'])){ // If the form addDrink has been submitted

				@ $db = new mysqli($dbserver, $dbuser, $dbpass, $dbname);

				if ($db->connect_error) {
					echo "could not connect: " . $db->connect_error;
					print("<br><a href=index.php>Return to home page </a>");
					exit();
				}

				if (isset($_POST['DrinkName']) && !empty($_POST['DrinkName'])) { // Check if the namefield isnt empty. 
					$NewDrinkName = $_POST['DrinkName'];
				}else{ // Else it takes the name it have before. 
					$NewDrinkName =$DrinkName;
				}
				
				if (isset($_POST['DrinkReceipt']) && !empty($_POST['DrinkReceipt'])) { // Check if the namefield isnt empty. 
					$NewDrinkReceipt = $_POST['DrinkReceipt'];
				}else{ // Else it takes the name it have before. 
					$NewDrinkReceipt = $DrinkReceipt;
				}

				
				$Ingredients = $_POST['Ingredients'];


				$updateDrink = "UPDATE Drinks SET DrinkName='$NewDrinkName', DrinkReceipt='$NewDrinkReceipt' WHERE DrinkId=$DrinkId"; // Insert the values into the database. 
		


				$stmt = $db->prepare($updateDrink);
				$stmt->bind_param('ss',$DrinkName,$DrinkReceipt);
				$stmt->execute(); 
				echo"<script>window.location = 'mypanel.php';</script>"; // Redirect to the panel after made changes. 
				$DrinkId = mysqli_insert_id($db); // Returns the last autogenerated id used in the last query. 

				foreach ($Ingredients as $index => $IngId){
					@ $db = new mysqli($dbserver, $dbuser, $dbpass, $dbname);

					$addDrinksIng = "INSERT INTO DrinksIng(DrinkId,IngId) VALUES ('$DrinkId','$IngId')";

					$stmt = $db->prepare($addDrinksIng);
					$stmt->execute();


				}
				/* foreach ($Ingredients as $index => $Id){
					@ $db = new mysqli($dbserver, $dbuser, $dbpass, $dbname);

					$updateDrinksIng = "UPDATE DrinksIng SET DrinksIng='$NewDrinkReceipt' WHERE DrinkId=$DrinkId";
					INSERT INTO DrinksIng(DrinkId,IngId) VALUES ('$DrinkId','$Id')";

					$stmt = $db->prepare($addDrinksIng);
					$stmt->execute();*/
			}

?>
<!Doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>UpdateDrink</title>
	</head>
	<body>
		<div class='c'>
		<div class="drinkside">
		<div  class="back">
			<a href="#" onClick="history.go(-1);return true;"><img class="knapp" src="Images/left-arrow.png"></a>
		</div>
		<div class="allforms">
			<form method="post">
				<h2>Update your drink</h2>
				<input class="fieldDrink" type="text" placeholder="<?php echo $DrinkName; ?> " name="DrinkName"></br>
				<div class="updateDrink">
				<div class='ingrblack'>
					<ul ><?php foreach($alling as $value){
		    			$newI = "<li id='existing'>" . $value . "<button type='button' class='btn' onclick='<?php test(); ?>'>X</button></li><br>";
		    			echo $newI; } ?> <!-- Print out each value that you can find into the ingredients array -->
		    		</ul>
		    	</div>
					<ul id="IngToDrink">
						
					</ul>
					<select class="select" id="Ingredients" name="addIng[]">
					<?php 
						while ($stmt->fetch()){
							echo"<option value='".$IngId."'>".$NameIng."</option>";
						}
					?>
					</select>
					<button class='button' id="connectDrinkIng" for="addIng"><img class="iconIMG" src="Images/plus.png" ></button></br>
					<button class='button2'>New Ingredient</button></br>
				</div>
				<input  class="receipt" type="text" placeholder="Receipt" name="DrinkReceipt"></br>
				<input class='button3' type="submit" name="updateDrink">
			</form>
		
			<form class="ingredientForm" method="post">
				<img src="Images/tri-2svart.png" class="tri"> <!-- triangle -->
				<div class="ingredientFromint">
				<h3>Add Ingredient</h3>
				<input class="fieldDrink 2" type="text" required placeholder="Name" name="NameIng"></br>
				<input class='button3' type="submit" name="addIng">
				</div>
				<img src="Images/tri-3svart.png" class="tri"> <!-- triangle -->
			</form>
			</div>

			<script type="text/javascript" src="addIng.js">
				
			
			</script>
		</div>
		</div>
	</body>
	<style>
	html{
		background-color: white;
	}
	body{
		background-color: white;
	}
	#white{
		background-color: white;
		width: 100%;
		display: block;
		overflow: hidden;

	}
		.c{
			padding-top:150px;
			position:relative;
			background-color: white;

		}
		.drinkimagepreview{
			width: 80%;
			max-width: 500px;
			margin:0 auto;
			display:block;
			margin-bottom:20px;		


		}
		#footerINC{
			background-color: #000;
			width: 100%;
		}
		p{
			font-family: 'open sans',helvetica;
			text-align: center;
		}
		/***************TEXT STYLE****************/

		h2{
			font-family: 'open sans',helvetica;
			font-weight: 800;
			text-transform: uppercase;
			font-size: 40px;
			color:black;
			margin:0;
			line-height: 45px;
			margin-bottom: 30px;
			text-align: center;
		}
		#pinkline{
			height: 2.5px;
			width: 280px;
			margin: 10px auto 15px auto;
			background-color: #e72262;
			padding: 0;

		}
		/***************BUTTONS****************/

		.button{
			width:25px;
			margin:0px;
			display: block;
			margin:auto;
			text-align: center;
			background-color: #e72262;
			color: #fff;
			border:solid 2px #e72262;
			border-radius: 50%;
			padding: 0;
			height:25px;
			font-size: 10px;
			float:left;
			cursor: pointer;
		} 
		.button2{
			margin: 30px auto 20px auto;
			text-align: center;
			font-family: 'open sans',helvetica;
			font-weight: 800;
			text-transform: uppercase;
			font-size: 14px;
			background-color: #e72262;
			color: #fff;
			border:none;
			width:200px;
			padding: 5px;
			-webkit-appearance: none;
			display: block;
			border-radius: 5px;
		} 

		.button:focus, .button2:focus, .button3:focus { 
			outline: none;
			cursor: pointer;
		}

		.button3{
			margin: 10px auto 20px auto;
			text-align: center;
			font-family: 'open sans',helvetica;
			font-weight: 800;
			text-transform: uppercase;
			font-size: 14px;
			background-color: #e72262;
			color: #fff;
			border:none;
			width:200px;
			padding: 5px;
			-webkit-appearance: none;
			border-radius: 5px;
			display: block;
		}

		.back{
			width: 20px;
			height: 20px;
			border-radius: 20px;
			padding:8px;
			position:absolute;
			left:10px;
			top:-180px;
		}
		.knapp{
			width: 40px;
			cursor: pointer;
		}
		.btn{
			background-color: #e72262;
			border-radius: 50%;
			border:none;
			margin-left: 10px;
			background-image: url(Images/error.png) center center  no-repeat;
			background-size: 100%;
			color:white;
			height:20px;
			width: 20px;
		}

		/***************TEXTFIELDS***************/
		.select{
			width:82%;
			margin:0  5px 0 2px;
			box-sizing: border-box;
			display: block;
			height:30px;
			float:left;
			font-family: 'open sans',helvetica;
			}

		.fieldDrink{
			width:70%;
			margin:0 auto;
			box-sizing: border-box;
			display: block;
			height:40px;
			padding:15px;
			font-size: 30px;
			text-align: center;
			font-family: 'open sans',helvetica;
			font-weight: 800;
			text-transform: uppercase;
			color:black;
			border:none;
		}
		.receipt{
			width:100%;
			max-width: 350px;
			margin:0 auto;
			box-sizing: border-box;
			display: block;
			height:20px;
			padding:15px;
			padding-bottom:100px;
			font-family: 'open sans',helvetica;
			border-color:#e72262;
			border-style: solid;

		}

		.addDrink{
			width:200px;
			margin:0px auto 0px auto;
			box-sizing: border-box;
			display: block;
			overflow: hidden;
			margin-bottom: -10px;
			text-align: left;
		}

		/***************ADDINGR***************/

		#IngToDrink{
			margin:0;
			padding:0;
			padding-bottom: 40px;
			font-family: 'open sans',helvetica;

		}

		#IngToDrink li{
			text-decoration: none;
			font-family: 'open sans',helvetica;
			list-style: none;
			margin:0;

		}
		.ingredientForm{
			display: none;
		}
		.ingredientForm.open{
			display: block;
			position: absolute;
			top:260px;
			width:70%;
			left:15%;
		}
		.ingredientFromint{
			background-color:black;
			height:150px;
			padding-top: 0;
			margin:0;
			padding:0;
		}
		.ingredientFromint h3{
			font-family: 'open sans',helvetica;
			font-weight: 800;
			text-transform: uppercase;
			font-size: 20px;
			color:white;
			margin:0;
			margin-top: -4px;
			text-align: center;
		}

		.ingredientFromint .fieldDrink{
			margin-top:10px;
		}
		.allforms{
			position: relative;
			max-width: 350px;
			background-color: white;
			margin: 0 auto;
		}
		.tri{
			width:100%;
		}
		.drinkside{
			position: relative;
			float:left;
			width:100%;
			text-align: left;
			margin-bottom: 20px;
		}
		
		.iconIMG{
			width: 15px;
			margin: 3px auto;
			text-align: center;
		}
		/* MEDIA MIN 600PX */

@media (min-width: 600px) {
		.c{
			padding-top:250px;
			position:relative;
			max-width: 1100px;
			margin: 0 auto;

		}
		.drinkside{
			overflow: hidden;
			float:left;
			width:50%;
			text-align: left;
			background-color: white;
			margin:0 0 20px 10px;
		}

		#imageside{
			height: 60vh;
			width: 50%;
			float: left; 
			display: inline;
			background-color: white;
			text-align: right;
			margin-bottom: 30px;
		}
		.drinkimagepreview{
			width: 80%;
			max-width: 300px;
			margin:0px auto 20px auto;
			display:inline;
			border: solid 2.5px #e72262 ;
			padding: 10px;
		}
		.allforms{
			width: 40%;
			float: left;
			display: inline;
			margin-top: 30px;
			margin-left: 20px;
			overflow: hidden;
			text-align: left;
			max-width: 500px;
		}
		#white{
			margin-bottom: 40px;
		}
	</style>
</html>